### ISSUE TITLE
PNG?

### ISSUE THREAD

**Issue by raiguard** [material-icons/material-icons#1]
Hello, I really appreciate what you've done here, and ordinarily I would be very content with it. However, my [project](https://github.com/raiguard/ModernGadgets) runs on Rainmeter, and you cannot use SVGs with Rainmeter.

Would it be possible to create PNGs of the icons for the repository? Ideally you would have a variety of sizes, but if not, I would probably be good with 48x48. Maybe 128x128 as well?

Thanks in advance!

**Comment by cyberalien** [comment]
Sure, its not hard to do.

I assume color should be black?

As for sizes, old Google repository had images in 24px, 48px, 96px, which is 1x, 2x and 4x of icon size.

Are these sizes acceptable or do you want 128px as well? 128px will be a bit blurry because icons are designed for 24x24 grid, so its not a good icon scaling.

**Comment by raiguard** [comment]
Ah, in that case I don't need 128x, I was just throwing a number out there. I am currently using the 48x48 images from material.io, which for the most part suits my needs just fine.

I actually need the icons to be white, not black. This is because I add my own color tint to them through Rainmeter, which you can see in this GIF:

![new demo skin 2](https://user-images.githubusercontent.com/3515394/55493255-d9be8100-55f5-11e9-87f2-a0bd36b9b412.gif)

I can programmatically change the accent color to whatever I want:

![2019-04-03 09_51_39](https://user-images.githubusercontent.com/3515394/55493432-299d4800-55f6-11e9-9703-baa63df0c29e.png)

Thanks for your help!

**Comment by cyberalien** [comment]
Added PNG files. Please check if they are suitable for your application.

White images are in png/white/{category}/{icon}.png
Default images are 24x24. 48x48 images have -2x suffix, 96x96 images have -4x suffix.

PNG files can be generated for any size and color, I've added build script for it in build/png.js.

**Comment by raiguard** [comment]
You, sir, are a hero. Seriously, thanks a million! This will make using the material icons so much easier. Downloading them from material.io was an enormous pain.

I'll be sure to add you to the special thanks section of my project's attributions. :D

**Comment by cyberalien** [comment]
Thanks.

**Comment by cyberalien** [comment]
Due to big size of files, I've moved PNG files to separate repository: https://github.com/cyberalien/material-design-icons-updated-png
