### ISSUE TITLE
Icons outdated

### ISSUE THREAD

**Issue by brandonmcconnell** [material-icons/material-icons#11]
I was comparing some of the icons with those in the official Google icon library hosted on Google Fonts, and noticed that the undo icon is different, with the core icon library using the flatter rounded undo icon.

I also noticed some icons (e.g. `nest_mini`) are not present in this repo.

This appears to be the case for a handful of icons. Can this repo please be updated to include all the latest icons?

Thank you! 🙏🏼

**Comment by brandonmcconnell** [comment]
I appear to be mistaken and was confusing the Material Icons set with the Material Symbols set. I would love to see another repo for similarly added SVG support for [Material Symbols](https://fonts.google.com/icons?icon.set=Material+Symbols).

Thanks again. Closing this ticket. 👋🏼

**Comment by cyberalien** [comment]
It is a bit tricky for Material Symbols. With all icon variations, it ends up being over 240k icons, so repository would be huge.

I've made an update script to maintain icon set for Iconify, but discarded everything except for regular 24px icons. Data is available here: https://github.com/iconify/icon-sets and tools are available to generate individual SVGs from it (see readme in that repository).

Then Google started maintaining their repository with regular updates, so icons are up to date in official repository: https://github.com/google/material-design-icons

See related issue: https://github.com/material-icons/material-icons-font/issues/8
