### ISSUE TITLE
The SVGs are not all 24x24

### ISSUE THREAD

**Issue by McHeisenburglar** [material-icons/material-icons#4]
Hey, love this repo! I'm creating a Sketch Library out of all of them, but a thing that gets in the way is that the SVGs are not actually all 24x24px. For example, "assignment_late" is 18x20px in this repo, while the SVG 24 that you download from material.io is actually 24x24px.

![2020-05-24 at 03 41](https://user-images.githubusercontent.com/34202623/82742526-7dc23900-9d70-11ea-8bef-a24891705ddd.jpg)

**Comment by cyberalien** [comment]
It is a normal behavior in Sketch.

All icons are 24x24, but when Sketch imports icon, it ignores bounding box. When you download any icon from material.io, it contains an empty rectangle `<path d="M0 0h24v24H0z" fill="none"/>` which fixes Sketch behavior.

You can use Iconify plug-in for Sketch to import icons, it will add empty rectangle before importing icon: https://github.com/iconify/iconify-sketch
