### ISSUE TITLE
checklist icon seems to be missing

### ISSUE THREAD

**Issue by Seiji42** [material-icons/material-icons#7]
I tried to use the checklist icon (listed on website here: https://material.io/resources/icons/?search=checklist&style=baseline), but I got an error instead. I checked for image data in the repo but I couldn't find it anywhere.

**Comment by cyberalien** [comment]
Sorry for slow response.

Update script automatically pulls latest icons from Google's website, but it is not ran too often, so sometimes there is a delay between new icons appearing on material.io and this repo. That icon has been added in one of updates this spring.
