### ISSUE TITLE
save all icon

### ISSUE THREAD

**Issue by hosseinse1919** [material-icons/material-icons#9]
this is code of save all icon (sharp) 
if u can add 

M 2 2 L 2 14 L 4 14 L 4 4 L 14 4 L 14 2 L 2 2 z M 6 6 L 6 21 L 21 21 L 21 10 L 17 6 L 6 6 z M 8 8 L 15 8 L 15 11 L 8 11 L 8 8 z M 13.5 14 C 14.883 14 16 15.117 16 16.5 C 16 17.883 14.883 19 13.5 19 C 12.117 19 11 17.883 11 16.5 C 11 15.117 12.117 14 13.5 14 z

**Comment by cyberalien** [comment]
Added
